repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.4.0
    hooks:
      - id: golangci-lint
        name: golangci-lint (all files)
        entry: golangci-lint run --config=.golangci.yaml
        types: [ go ]